const entries = [
  {
      "_id": "5c9fa1b880b8c118ff22fbb9",
      "name": "Cowboy Hats",
      "price": 45.45,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Real Cowbois",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 27,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc7",
      "name": "Ranch",
      "price": 3000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Kraft",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 41,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbdf",
      "name": "Longhorn",
      "price": 1500,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Texas A&M",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 65,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf7",
      "name": "Charcoal Grill",
      "price": 339.39,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Griller Enthusiasts",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 89,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba2",
      "name": "Beaver",
      "price": 150,
      "bulletOne": "Big slappy tails",
      "bulletTwo": "Have massive impacts on their ecosystem",
      "bulletThree": "Always chewing trees",
      "sellerName": "The Dam Busters",
      "description": "The large front teeth of the beaver never stop growing. The beavers constant gnawing on wood helps to keep their teeth from growing too long.",
      "productID": 4,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba5",
      "name": "Snow Skis",
      "price": 345.45,
      "bulletOne": "Twice as fun as a snowboard",
      "bulletTwo": "Glide down a mountain on powdery white snow",
      "bulletThree": "Two skis in a pair",
      "sellerName": "Panda Express",
      "description": "Disclaimer: Running into a tree will hurt!!",
      "productID": 7,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fb9f",
      "name": "Maple Syrup",
      "price": 10.25,
      "bulletOne": "Delicious Canadian Nectar",
      "bulletTwo": "Great with cereal",
      "bulletThree": "Getnly milked from the sturdiest of trees",
      "sellerName": "Quebec",
      "description": "This isn't aunt gemimas crap. The greatest thing since forever ago.",
      "productID": 1,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba6",
      "name": "Maple Taffy",
      "price": 0.5,
      "bulletOne": "Tacky Maple Goodness",
      "bulletTwo": "Just Plain Delicious",
      "bulletThree": "Words Can't Describe It",
      "sellerName": "Billy'z Candy",
      "description": "What's better than maple syrup? Boiled maple syrup poured over snow and picked up with a popsicle stick is what.",
      "productID": 8,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba0",
      "name": "Poutine",
      "price": 7.34,
      "bulletOne": "Fries",
      "bulletTwo": "Cheese",
      "bulletThree": "Gravy",
      "sellerName": "La Belle Province",
      "description": "Canadian cheese fries worth dying for. Top it with whatever you want cause its already incredibly unhealthy.",
      "productID": 2,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba1",
      "name": "Moose",
      "price": 4200,
      "bulletOne": "Great for traversing deep snow drifts.",
      "bulletTwo": "Bigger than you think they are.",
      "bulletThree": "",
      "sellerName": "The Horses",
      "description": "Get your own trusty steed to ride through the winter in glory.",
      "productID": 3,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba3",
      "name": "Maple Leaves",
      "price": 1.99,
      "bulletOne": "Genuine maple leaves",
      "bulletTwo": "Sourced from maple trees",
      "bulletThree": "10 per order!",
      "sellerName": "Canadiens",
      "description": "The most beautiful leaf in all of the world. A symbol of pride and integrity for the greatest nation on earth.",
      "productID": 5,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba8",
      "name": "Don Cherry",
      "price": 14000000,
      "bulletOne": "Former Hockey Player",
      "bulletTwo": "Former Hockey Coach",
      "bulletThree": "Currently a national treasure",
      "sellerName": "Hockey Night In Canada",
      "description": "Never wears the same suit twice and has been the voice of Hockey Night In Canada for over 30 years.",
      "productID": 10,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbaa",
      "name": "Hockey Stick",
      "price": 89.99,
      "bulletOne": "Right handed",
      "bulletTwo": "80 flex",
      "bulletThree": "Probably won't break, but don't test it.",
      "sellerName": "CCM",
      "description": "A long, thin implement with a curved end, used to hit or direct the puck or ball in ice hockey or field hockey.",
      "productID": 12,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb8",
      "name": "Cowboy Boots",
      "price": 99.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Real Cowbois",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 26,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbbf",
      "name": "Six Shooter",
      "price": 666.666,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.Six Bullets",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Colt",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 33,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc5",
      "name": "Houston Astros",
      "price": 1700000000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Texas Rangers",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 39,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf3",
      "name": "Sandles with BUILT in Bottle Opener",
      "price": 99999,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Who had this idea?",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 85,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb0",
      "name": "Molson",
      "price": 2.39,
      "bulletOne": "It's a beer",
      "bulletTwo": "There are different variates",
      "bulletThree": "Made in Canada",
      "sellerName": "Molson",
      "description": "Founded in 1786 in Montreal. That's older than me for sure.",
      "productID": 18,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb5",
      "name": "Hawaiian Pizza",
      "price": 24.86,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Delicious Pizza Co",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 23,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbcc",
      "name": "Coke",
      "price": 1.5,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Pepsi",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 46,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd2",
      "name": "Homecoming Mum",
      "price": 67.69,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Nonsensical Things",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 52,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe4",
      "name": "Whataburger Spicy Ketchup 36oz Bottle",
      "price": 6.34,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "What's A Burger",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 70,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe5",
      "name": "Street Tacos",
      "price": 0.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Frodo's Food Truck",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 71,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbfa",
      "name": "Cocaine",
      "price": 9.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "El Chapo",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 92,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbfb",
      "name": "Chicken Fried Steak",
      "price": 7.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Steak Fried Chicken",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 93,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbfc",
      "name": "Bowie Knife",
      "price": 99.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Generic Company Name",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 94,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc2",
      "name": "Kolaches",
      "price": 0.74,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Kolache Factory",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 36,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd6",
      "name": "Texas Tech Keycap Set",
      "price": 3.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "KeyCaps",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 56,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe6",
      "name": "Tickets to Schlitterbahn",
      "price": 78,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Fandango",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 72,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf6",
      "name": "Bolo Tie",
      "price": 26.89,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "GoGo Gadget",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 88,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb6",
      "name": "Wayne Gretzky",
      "price": 2857,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.Fastest player to score 1000 points",
      "bulletTwo": "Second fastest player to score 1000 pointsLorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Always chewing treesLorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Hockey Hall of Fame",
      "description": "The large front teeth of the beaver never stop growing. The beavers constaLorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.nt gnawing on wood helps to keep their teeth from growing too long.",
      "productID": 24,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbbb",
      "name": "Texas Flag",
      "price": 19.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Texas Flag Corp",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 29,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbcd",
      "name": "Rocking Chair",
      "price": 187.88,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "International Federation of Rocking Chair Enthusiasts",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 47,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbfe",
      "name": "Scooter",
      "price": 37.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "The Great Tool Maker",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 96,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb7",
      "name": "Cofee Crisp",
      "price": 1.32,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Chocolate Coffee Corp",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 25,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb3",
      "name": "Canadian Geese",
      "price": 1000000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Canada",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 21,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd1",
      "name": "Tumbleweed, 1ct",
      "price": 10.67,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "The Hell Is This?",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 51,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd4",
      "name": "Homecoming Garter",
      "price": 34.21,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Nonsensical Things",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 54,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe8",
      "name": "Houston Rockets' Jersey #99",
      "price": 99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "NASA",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 74,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fc00",
      "name": "Standup Paddle Board",
      "price": 204,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Who Came Up With This As Coming From Texas?",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 98,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fc01",
      "name": "Prarie Dog",
      "price": 42.56,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Hedgehog",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 99,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbac",
      "name": "Justin Trudeau",
      "price": 172400,
      "bulletOne": "Handsome",
      "bulletTwo": "Prime Minster of Canada",
      "bulletThree": "Son of Pierre Trudeau",
      "sellerName": "Parliament",
      "description": "Born in Montreal, he followed his father's footsteps to become the prime minster of Canada.",
      "productID": 14,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd7",
      "name": "Official Blue Bell Ice Cream T-Shirt",
      "price": 8.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Blue Bell Official",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 57,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd8",
      "name": "H-E-B Houston Blend Coffee",
      "price": 14.89,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "H-E-B",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 58,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbdb",
      "name": "70 Mile Long Country Road",
      "price": 87500000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Pothole Maker Co",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 61,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe3",
      "name": "Texas A&M Beer Cozy",
      "price": 1.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Pi Kappa Alpha",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 69,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbee",
      "name": "Jalapeno Peppers",
      "price": 1.58,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Jalapeno Buisness",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 80,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbab",
      "name": "Hockey Puck",
      "price": 20.2,
      "bulletOne": "Galvanized Rubber",
      "bulletTwo": "Wouldn't feel good to get hit by one",
      "bulletThree": "Black",
      "sellerName": "CCM",
      "description": "Disk made of vulcanized rubber that serves the same functions in various games as a ball does in ball games",
      "productID": 13,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb4",
      "name": "Free Health Care",
      "price": 0,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "The Government",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 22,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc4",
      "name": "Buddy Holly Glasses",
      "price": 63.12,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Buddy Holly",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 38,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc9",
      "name": "Guitar",
      "price": 154.25,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "The Guy Tar Shop",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 43,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbef",
      "name": "Cactus",
      "price": 6.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Pillow Factory",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 81,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fc02",
      "name": "Sun Screen",
      "price": 5.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "I'm Out of Company Names",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 100,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbbc",
      "name": "Saddle",
      "price": 150,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Real Cowbois",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 30,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba4",
      "name": "Smarties",
      "price": 1,
      "bulletOne": "Perfect for your friends",
      "bulletTwo": "Comes in an assortment of colors",
      "bulletThree": "Red, Orange, Yellow, Blue, Green, Mauve, Pink, Brown",
      "sellerName": "Dummies",
      "description": "Oblate spheroids with a minor axis of about 5 mm and a major axis of about 12 mm",
      "productID": 6,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbbd",
      "name": "Lasso",
      "price": 110,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Real Cowbois",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 31,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc0",
      "name": "Shiner Bock",
      "price": 1.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Dull Back",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 34,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc8",
      "name": "Willie Nelson",
      "price": 337,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Nelson's Willie",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 42,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbca",
      "name": "Spurs",
      "price": 1600000000,
      "bulletOne": "A basketball team. At least I think it's a basketball team.",
      "bulletTwo": "If they are a basketball team then they play basketball.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "LA Lakers",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 44,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbce",
      "name": "Iced Sweet Tea",
      "price": 2.1,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Big Tee Co.",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 48,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd3",
      "name": "Amy's Ice Cream Gift Card",
      "price": 50,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Amy's Ice Cream",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 53,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd5",
      "name": "Austin Texas Novelty Keycap",
      "price": 0.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "KeyCaps",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 55,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe1",
      "name": "Tito's Vodka",
      "price": 34.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Tits",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 67,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbeb",
      "name": "Catfish",
      "price": 14.57,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Horsewhale",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 77,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbec",
      "name": "Queso",
      "price": 1.23,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Cheeeeeese",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 78,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf1",
      "name": "Texas Longhorns Cap",
      "price": 50,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "University of Texas Bake Sale",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 83,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb1",
      "name": "Chris Hadfield",
      "price": 145338,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Canadian Space Agency",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 19,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc3",
      "name": "Texas BBQ",
      "price": 12.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Like No Other",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 37,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbad",
      "name": "Canadian Tire Money",
      "price": 3.25,
      "bulletOne": "Basicly it's rewards for shopping",
      "bulletTwo": "Kinda self explanatory",
      "bulletThree": "",
      "sellerName": "Canadian Tire",
      "description": "Earned by shopping at Canadian Tire. Completely worthless everywhere else.",
      "productID": 15,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba7",
      "name": "Milk in a Bag",
      "price": 4.19,
      "bulletOne": "Yes. It really does come in a bag.",
      "bulletTwo": "Really not that weird.",
      "bulletThree": "",
      "sellerName": "Never Seen This Before, Eh",
      "description": "What's more to say it's milk in a bag.",
      "productID": 9,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbdc",
      "name": "Frito Pie, one serving",
      "price": 1.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Fritos",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 62,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe0",
      "name": "Way Overpriced Studio Apartment - Downtown Austin",
      "price": 2000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Zillow",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 66,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe7",
      "name": "Arlen Propane Tank, 20lbs",
      "price": 35.69,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Strickland Propane",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 73,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe9",
      "name": "Rattle Snake",
      "price": 100.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Baby Toys",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 75,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbfd",
      "name": "Chaps",
      "price": 68.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Chapstick Company",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 95,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf9",
      "name": "Road Bike",
      "price": 1299,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "This isn't even remotely a texas thing",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 91,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbaf",
      "name": "Canadian Bacon",
      "price": 2.64,
      "bulletOne": "It's just ham.",
      "bulletTwo": "But so is bacon.",
      "bulletThree": "So what's the big deal?",
      "sellerName": "The Real Meatz",
      "description": "Back bacon that is cured, smoked and fully cooked, trimmed into cylindrical medallions, and thickly sliced.",
      "productID": 17,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbb2",
      "name": "French for Dummies",
      "price": 10000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "The Rest of Canada",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 20,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbbe",
      "name": "Lone Star Beer",
      "price": 3.21,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Crowded Moon Wine",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 32,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc6",
      "name": "AR-15",
      "price": 399,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "AARP",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 40,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbcf",
      "name": "King of the Hill Season 6 DVD box set",
      "price": 12.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Family Guy",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 49,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd9",
      "name": "Bucee's $25 Gift Card",
      "price": 30.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Bucee's",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 59,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf2",
      "name": "Cornhole",
      "price": 78,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Again Not From Texas",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 84,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbdd",
      "name": "Dr. Pepper 56 Ct.",
      "price": 56,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Coca-Cola",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 63,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbea",
      "name": "Bluebonnet",
      "price": 0.23,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "The Rose Alliance",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 76,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf0",
      "name": "Ultimate Frisbee",
      "price": 200,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "This ain't even from Texas",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 82,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbc1",
      "name": "Yeti Cooler",
      "price": 299.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Sasquatch Ice",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 35,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbda",
      "name": "Bucee's Beaver Nuggets, 48oz Bag",
      "price": 24.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Bucee's",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 60,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbde",
      "name": "Bottle of Matthew McConaughey's Sweat",
      "price": 1000000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Matthew McConaughey's Aunt's Neighbor's Son",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 64,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbe2",
      "name": "Dublin Dr. Pepper",
      "price": 1.5,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Coca-Cola",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 68,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf5",
      "name": "Sun Hat",
      "price": 23.56,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Hat Company",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 87,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbff",
      "name": "Cornbread",
      "price": 8.34,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Cornbread.com",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 97,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbba",
      "name": "The Alamo",
      "price": 2784503,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Texass",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 28,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbcb",
      "name": "Belt Buckle",
      "price": 49.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Levi's",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 45,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fba9",
      "name": "Winter Jackets",
      "price": 250,
      "bulletOne": "You need one when it's cold",
      "bulletTwo": "Get a good one or you'll freeze your ass off.",
      "bulletThree": "",
      "sellerName": "SnowStorm Hardware",
      "description": "Warm, light, and colorful what more are you looking for in a jacket?",
      "productID": 11,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbae",
      "name": "Ketchup Chips",
      "price": 3.74,
      "bulletOne": "Can't find em in the US",
      "bulletTwo": "Bag comes with a bunch of chips in it",
      "bulletThree": "Flavored like ketchup",
      "sellerName": "Lays",
      "description": "Ketchup and chips are weird combo, but oddly good.",
      "productID": 16,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbd0",
      "name": "Whataburger #1 Combo Meal",
      "price": 9.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "McDonald's",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 50,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbed",
      "name": "Mateo's Salsa",
      "price": 3.23,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Mateo's Dance Co.",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 79,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf4",
      "name": "Hipster Shades",
      "price": 1024,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Dank Pants",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 86,
      "__v": 0
  },
  {
      "_id": "5c9fa1b880b8c118ff22fbf8",
      "name": "Football",
      "price": 215000000,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "Concussion Factory",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 90,
      "__v": 0
  },
  {
      "_id": "5cae0381a3be7c1af2641070",
      "__v": 0
  },
  {
      "_id": "5cae0916605e115731433a33",
      "name": "Sun Screen",
      "price": 5.99,
      "bulletOne": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      "bulletTwo": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesen.",
      "bulletThree": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "sellerName": "I'm Out of Company Names",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusc.",
      "productID": 9999,
      "__v": 0
  }
];

module.exports = entries;